### ISSUE TITLE
Flexible field with custom resolver complain about groups being null

### ISSUE THREAD

**Issue by TheSETJ** [whitecube/nova-flexible-content#236]
Hey, before anything else, I need to say I appreciate your efforts in developing such a beautiful piece of art. It is awesome.

---

Consider having a `Post` model (in `posts` table) and a `Category` model (in `categories` table). A `Post` can have many `Category`s (typical has many relationship). I want the admin to be able to add categories on the same form they're creating the post. Here is my flexible field for the situation:

```php
\Whitecube\NovaFlexibleContent\Flexible::make(__('Categories'), 'categories')
    ->addLayout(__('Category'), 'category', [
        Text::make(__('Text'))
    ])->resolver(\App\Nova\Flexible\Resolvers\CategoryResolver::class)
```

`get` and `set` methods of `CategoryResolver` are almost empty, I'm just logging parameters to see what I get.

When I open the form, Nova displays an error about *calling map() on null*. Here is the error's stack trace from the log file:

```log
[2020-11-07 16:33:58] local.ERROR: Call to a member function map() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function map() on null at /mnt/storage/dev/hamsaa/admin-panel/vendor/whitecube/nova-flexible-content/src/Flexible.php:404)
[stacktrace]
#0 /mnt/storage/dev/hamsaa/admin-panel/vendor/whitecube/nova-flexible-content/src/Flexible.php(250): Whitecube\\NovaFlexibleContent\\Flexible->resolveGroups(NULL)
#1 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Fields/FieldCollection.php(51): Whitecube\\NovaFlexibleContent\\Flexible->resolve(Object(App\\Post))
#2 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Laravel\\Nova\\Fields\\FieldCollection->Laravel\\Nova\\Fields\\{closure}(Object(Whitecube\\NovaFlexibleContent\\Flexible), 6)
#3 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Fields/FieldCollection.php(53): Illuminate\\Support\\Collection->each(Object(Closure))
#4 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/ResolvesFields.php(194): Laravel\\Nova\\Fields\\FieldCollection->resolve(Object(App\\Post))
#5 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/ResolvesFields.php(223): Laravel\\Nova\\Resource->creationFields(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#6 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Http/Controllers/CreationFieldController.php(23): Laravel\\Nova\\Resource->creationFieldsWithinPanels(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest))
#7 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\CreationFieldController->index(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'posts')
#8 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#9 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\CreationFieldController), 'index')
#10 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#11 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#12 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /mnt/storage/dev/hamsaa/admin-panel/vendor/whitecube/nova-flexible-content/src/Http/Middleware/InterceptFlexibleAttributes.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Whitecube\\NovaFlexibleContent\\Http\\Middleware\\InterceptFlexibleAttributes->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#30 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /mnt/storage/dev/hamsaa/admin-panel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /mnt/storage/dev/hamsaa/admin-panel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 /mnt/storage/dev/hamsaa/admin-panel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 /mnt/storage/dev/hamsaa/admin-panel/server.php(21): require_once('/mnt/storage/de...')
#59 {main}
"}
```

I took a look at the code and found out that `$this->groups` in `Flexible` class is null. Based on the documentation, there is nothing I can do about groups (except in `set` method which is empty for now and it hasn't called yet). What am I missing?

**Comment by manogi** [comment]
Please post your Resolver class.

**Comment by TheSETJ** [comment]
@manogi

As I said, it's almost empty, but if it helps, here you are:

```php
class CategoryResolver implements ResolverInterface
{
    /**
     * get the field's value
     *
     * @param  mixed  $resource
     * @param  string $attribute
     * @param  Whitecube\NovaFlexibleContent\Layouts\Collection $layouts
     * @return Illuminate\Support\Collection
     */
    public function get($resource, $attribute, $layouts)
    {
        info($resource); info($attribute); info($layouts);
    }

    /**
     * Set the field's value
     *
     * @param  mixed  $model
     * @param  string $attribute
     * @param  Illuminate\Support\Collection $groups
     * @return void
     */
    public function set($model, $attribute, $groups)
    {
        info($model); info($attribute); info($groups);
    }
}
```

**Comment by TheSETJ** [comment]
I feel like an idiot now. Just after commenting about how my Resolver class, looks like, I realized `get` should return an instance of `Illuminate\Support\Collection`.

When I generated this Resolver class and I faced the error, I was thinking: _I didn't touch anything yet, so it should work right away._ 😒

I'll add a `return collect()` statement to the `get` method then test it again and let you know of the result.

**Comment by manogi** [comment]
Hey there - the get method is expected to return a collection. The error will co away when your make it return en empty collection like this:

```
return collect([]);
```

**Comment by manogi** [comment]
Yes, you got it - if often helps to explain the problem ;-)

**Comment by manogi** [comment]
BTW I like your idea of using Flexible to attach Relationships. Will you make a custom field that lets you also create a category on the fly?

**Comment by TheSETJ** [comment]
> BTW I like your idea of using Flexible to attach Relationships.

I've done this because documentation mentioned that it's possible.

> Will you make a custom field that lets you also create a category on the fly?

You mean I wrap a Flexible in a custom field? By the way, I didn't create any custom field yet.

**Comment by manogi** [comment]
Yes, maybe - I thought it would be nice to just have something like 

``` php
FlexibleHasMany::make('Category', 'category')
```

Or something along those lines.

But the first thing would probably to extract the Layout to your own custom layout, [see here in the docs](https://whitecube.github.io/nova-flexible-content/#/?id=custom-layout-classes)

Well, all of this does not really belong here. By the way, I am also just a guest here, so you should probably close the issue because I can't. Have fun coding!

**Comment by TheSETJ** [comment]
I confirm, after adding `return collect()` to `get` method, no error occurs.
