### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by rklugman** [whitecube/nova-flexible-content#338]
Please could you change your composer requirements to support Nova 4 - thanks

**Comment by voidgraphics** [comment]
Does it just work out of the box without any changes?

I will reiterate our need for an additional maintainer (see https://github.com/whitecube/nova-flexible-content/discussions/326). This is especially true now that Nova 4 is out, since we do not have a license for it, and currently do not have plans to get one. We do not have the means to test for compatibility ourselves.

**Comment by rklugman** [comment]
I'm really not sure how Nova 4 would impact this package to be honest

**Comment by stonkeep** [comment]
```
TypeError: Cannot read properties of undefined (reading '_c')
at Proxy.render (nova-flexible-content:1:164128)
    at zn (runtime-core.esm-bundler.js:893:44)
    at we.fn (runtime-core.esm-bundler.js:5030:57)
    at we.run (reactivity.esm-bundler.js:167:25)
    at R (runtime-core.esm-bundler.js:5156:9)
    at j (runtime-core.esm-bundler.js:4939:9)
    at N (runtime-core.esm-bundler.js:4897:17)
    at g (runtime-core.esm-bundler.js:4489:21)
    at E (runtime-core.esm-bundler.js:4685:13)
    at B (runtime-core.esm-bundler.js:4856:13)
```

**Comment by bashgeek** [comment]
> I'm really not sure how Nova 4 would impact this package to be honest. I'm going to make a fork and see how it reacts

Lots of changes under the hood:
- Replacement of Vue Router with Inertia
- Laravel Mix upgrade from version 1 to 6

Hence, quite some updates to all third-party plugins are required, this is will take a little while.
